/*
 * Board-side preprocessing for the 360x640 RPS model:
 *   1. resize the full 720x1280 grayscale frame to 360x640
 *   2. diff = abs(frame_t - frame_t_minus_gap)
 *   3. values below the threshold become zero
 *   4. multiply the remaining difference by the configured gain and clip
 *
 * The model outputs ROCK, PAPER and SCISSORS logits. IDLE is generated by
 * the motion gate and is not a model output.
 */

#include <cstdio>
#include <cstring>
#include <cmath>
#include <cerrno>
#include <sys/stat.h>
#include <sys/types.h>
#include "common.hpp"
#include "utils.hpp"

namespace utils {
GestureClass ArgmaxProbs(const float probs[APP_GESTURE_COUNT], float* out_conf) {
    int best_idx = 0;
    float best_prob = probs[0];
    for (int i = 1; i < APP_GESTURE_COUNT; i++) {
        if (probs[i] > best_prob) {
            best_prob = probs[i];
            best_idx = i;
        }
    }
    if (out_conf) *out_conf = best_prob;
    return static_cast<GestureClass>(best_idx);
}
} // namespace utils

RuntimeRpsParams g_runtime_rps_params;

static int ClampRuntimeInt(int value, int low, int high) {
    return value < low ? low : (value > high ? high : value);
}

void PrintRuntimeRpsParams() {
    printf("[RPS_PARAM] gap=%d threshold=%d gain=%d idle_pixels=%d windup=%d vote=%d\n",
           g_runtime_rps_params.frame_gap.load(),
           g_runtime_rps_params.diff_threshold.load(),
           g_runtime_rps_params.diff_gain.load(),
           g_runtime_rps_params.idle_min_active_pixels.load(),
           g_runtime_rps_params.wind_up_frames.load(),
           g_runtime_rps_params.vote_frames.load());
    fflush(stdout);
}

static const char* A1_INPUT_DUMP_DIR = "/tmp/a1model_inputs";
static const int A1_INPUT_DUMP_MAX = 120;
static int g_a1_input_dump_count = 0;
static bool g_a1_input_dump_dir_ready = false;

static void EnsureA1InputDumpDir() {
    if (g_a1_input_dump_dir_ready) return;
    if (mkdir(A1_INPUT_DUMP_DIR, 0777) != 0 && errno != EEXIST) {
        if (RuntimeLogAtLeast(RuntimeLogMode::VERIFY)) {
            printf("[RPS] failed to create dump dir: %s errno=%d\n",
                   A1_INPUT_DUMP_DIR, errno);
        }
        return;
    }
    g_a1_input_dump_dir_ready = true;
}

static void DumpA1InputPgm(const uint8_t* data, int width, int height, int frame_count) {
    if (!RPS_DUMP_A1_INPUTS || !data || width <= 0 || height <= 0 ||
        g_a1_input_dump_count >= A1_INPUT_DUMP_MAX) {
        return;
    }

    EnsureA1InputDumpDir();
    if (!g_a1_input_dump_dir_ready) return;

    char path[160];
    snprintf(path, sizeof(path), "%s/a1in_%06d_frame_%06d.pgm",
             A1_INPUT_DUMP_DIR, g_a1_input_dump_count, frame_count);
    FILE* fp = fopen(path, "wb");
    if (!fp) return;
    fprintf(fp, "P5\n%d %d\n255\n", width, height);
    fwrite(data, 1, static_cast<size_t>(width) * static_cast<size_t>(height), fp);
    fclose(fp);
    g_a1_input_dump_count++;
}

void RPSCLASSIFIER::RunSingleFrameInference(
        ssne_tensor_t* img, float out_probs[APP_GESTURE_COUNT]) {
    for (int i = 0; i < APP_GESTURE_COUNT; i++) out_probs[i] = 0.f;

    const uint8_t* raw_src = static_cast<const uint8_t*>(get_data(*img));
    if (!raw_src) {
        out_probs[static_cast<int>(GestureClass::IDLE)] = 1.f;
        return;
    }

    const int src_w = img_shape[0];
    const int src_h = img_shape[1];
    const int dst_w = model_shape[0];
    const int dst_h = model_shape[1];
    const int pixels = dst_w * dst_h;
    const int frame_gap = ClampRuntimeInt(
        g_runtime_rps_params.frame_gap.load(), 1, RPS_MAX_RUNTIME_FRAME_GAP);
    const int diff_threshold = ClampRuntimeInt(
        g_runtime_rps_params.diff_threshold.load(), 0, 255);
    const int diff_gain = ClampRuntimeInt(
        g_runtime_rps_params.diff_gain.load(), 1, 32);
    const int idle_min_active = ClampRuntimeInt(
        g_runtime_rps_params.idle_min_active_pixels.load(), 0, pixels);

    if (src_w <= 0 || src_h <= 0 || dst_w <= 0 || dst_h <= 0) {
        out_probs[static_cast<int>(GestureClass::IDLE)] = 1.f;
        return;
    }

    for (int dy = 0; dy < dst_h; dy++) {
        const int sy = static_cast<int>(static_cast<long>(dy) * src_h / dst_h);
        for (int dx = 0; dx < dst_w; dx++) {
            const int sx = static_cast<int>(static_cast<long>(dx) * src_w / dst_w);
            letterbox_buf[dy * dst_w + dx] = raw_src[sy * src_w + sx];
        }
    }

    frame_count++;
    uint8_t* diff_data = static_cast<uint8_t*>(get_data(diff_tensor));
    if (!diff_data) {
        out_probs[static_cast<int>(GestureClass::IDLE)] = 1.f;
        return;
    }

    int active_pixels = 0;
    if (history_count >= frame_gap) {
        const int past_index =
            (history_head - frame_gap + RPS_MAX_RUNTIME_FRAME_GAP) %
            RPS_MAX_RUNTIME_FRAME_GAP;
        const uint8_t* past_frame = frame_history[past_index];
        for (int i = 0; i < pixels; i++) {
            int delta = static_cast<int>(letterbox_buf[i]) -
                        static_cast<int>(past_frame[i]);
            int absolute_delta = delta < 0 ? -delta : delta;
            if (absolute_delta < diff_threshold) absolute_delta = 0;
            const int amplified = absolute_delta * diff_gain;
            diff_data[i] = static_cast<uint8_t>(amplified > 255 ? 255 : amplified);
            if (diff_data[i] != 0) active_pixels++;
        }
    } else {
        memset(diff_data, 0, pixels);
    }

    memcpy(frame_history[history_head], letterbox_buf, pixels);
    history_head = (history_head + 1) % RPS_MAX_RUNTIME_FRAME_GAP;
    if (history_count < RPS_MAX_RUNTIME_FRAME_GAP) history_count++;

    if (active_pixels < idle_min_active) {
        out_probs[static_cast<int>(GestureClass::IDLE)] = 1.f;
        return;
    }

    // Width 360 is not divisible by 16, so bypass the vendor offline resize
    // pipe and copy the already prepared uint8 tensor directly.
    uint8_t* model_input = static_cast<uint8_t*>(get_data(inputs[0]));
    if (!model_input) {
        out_probs[static_cast<int>(GestureClass::IDLE)] = 1.f;
        return;
    }
    memcpy(model_input, diff_data, pixels);
    DumpA1InputPgm(model_input, dst_w, dst_h, frame_count);

    if (ssne_inference(model_id, 1, inputs)) {
        if (RuntimeLogEnabled()) fprintf(stderr, "[RPS] ssne_inference failed\n");
        out_probs[static_cast<int>(GestureClass::IDLE)] = 1.f;
        return;
    }

    const int get_output_ret = ssne_getoutput(model_id, 1, outputs);
    const float* raw = static_cast<const float*>(get_data(outputs[0]));
    if (get_output_ret != 0 || !raw) {
        if (RuntimeLogEnabled()) {
            fprintf(stderr, "[RPS] ssne_getoutput failed ret=%d\n", get_output_ret);
        }
        out_probs[static_cast<int>(GestureClass::IDLE)] = 1.f;
        return;
    }

    if (RPS_DEBUG_NPU_RAW && RuntimeLogAtLeast(RuntimeLogMode::VERIFY)) {
        printf("[RPS_NPU] frame=%d ROCK=%.6f PAPER=%.6f SCISSORS=%.6f\n",
               frame_count, raw[0], raw[1], raw[2]);
    }

    float max_value = raw[0];
    for (int i = 1; i < MODEL_OUTPUT_COUNT; i++) {
        if (raw[i] > max_value) max_value = raw[i];
    }

    float sum = 0.f;
    float model_probs[MODEL_OUTPUT_COUNT] = {0.f, 0.f, 0.f};
    for (int i = 0; i < MODEL_OUTPUT_COUNT; i++) {
        model_probs[i] = expf(raw[i] - max_value);
        sum += model_probs[i];
    }
    if (sum <= 0.f) sum = 1.f;
    for (int i = 0; i < MODEL_OUTPUT_COUNT; i++) model_probs[i] /= sum;

    out_probs[static_cast<int>(GestureClass::IDLE)] = 0.f;
    out_probs[static_cast<int>(GestureClass::ROCK)] = model_probs[0];
    out_probs[static_cast<int>(GestureClass::PAPER)] = model_probs[1];
    out_probs[static_cast<int>(GestureClass::SCISSORS)] = model_probs[2];
}

GestureClass RPSCLASSIFIER::GetCounterMove(GestureClass gesture) {
    switch (gesture) {
        case GestureClass::ROCK: return GestureClass::PAPER;
        case GestureClass::PAPER: return GestureClass::SCISSORS;
        case GestureClass::SCISSORS: return GestureClass::ROCK;
        default: return GestureClass::IDLE;
    }
}

void RPSCLASSIFIER::UpdateStateMachine(GestureClass current_gesture,
                                       float current_confidence,
                                       RpsResult* result) {
    state_frame_count++;
    switch (game_state) {
        case GameState::IDLE: {
            const int wind_up_frames = ClampRuntimeInt(
                g_runtime_rps_params.wind_up_frames.load(), 1, TemporalBuffer::CAPACITY);
            if (temporal_buffer.ConsecutiveNonIdle(wind_up_frames) >= wind_up_frames) {
                game_state = GameState::WIND_UP;
                state_frame_count = 0;
            }
            result->game_state = GameState::IDLE;
            result->human_gesture = GestureClass::IDLE;
            result->ai_counter = GestureClass::IDLE;
            result->confidence = 0.f;
            result->is_locked = false;
            break;
        }
        case GameState::WIND_UP: {
            float vote_confidence = 0.f;
            const int vote_frames = ClampRuntimeInt(
                g_runtime_rps_params.vote_frames.load(), 1, TemporalBuffer::CAPACITY);
            GestureClass voted = temporal_buffer.GetWeightedVote(
                vote_frames, &vote_confidence);
            if (voted == GestureClass::IDLE) {
                voted = current_gesture;
                vote_confidence = current_confidence;
            }
            locked_prediction = voted;
            game_state = GameState::PREDICTED;
            state_frame_count = 0;
            result->human_gesture = locked_prediction;
            result->ai_counter = GetCounterMove(locked_prediction);
            result->confidence = vote_confidence;
            result->game_state = GameState::PREDICTED;
            result->is_locked = true;
            break;
        }
        case GameState::PREDICTED:
            result->human_gesture = locked_prediction;
            result->ai_counter = GetCounterMove(locked_prediction);
            result->confidence = current_confidence;
            result->game_state = GameState::PREDICTED;
            result->is_locked = true;
            if (state_frame_count >= DISPLAY_HOLD_FRAMES) {
                game_state = GameState::DISPLAY;
                state_frame_count = 0;
            }
            break;
        case GameState::DISPLAY:
            result->human_gesture = locked_prediction;
            result->ai_counter = GetCounterMove(locked_prediction);
            result->confidence = current_confidence;
            result->game_state = GameState::DISPLAY;
            result->is_locked = true;
            if (temporal_buffer.ConsecutiveIdle(IDLE_RESET_FRAMES) >= IDLE_RESET_FRAMES) {
                game_state = GameState::IDLE;
                state_frame_count = 0;
                locked_prediction = GestureClass::IDLE;
            }
            break;
    }
}

void RPSCLASSIFIER::Initialize(std::string& model_path,
                               std::array<int, 2>* in_img_shape,
                               std::array<int, 2>* in_model_shape) {
    img_shape = *in_img_shape;
    model_shape = *in_model_shape;
    game_state = GameState::IDLE;
    state_frame_count = 0;
    locked_prediction = GestureClass::IDLE;
    frame_count = 0;

    frame_pixels = img_shape[0] * img_shape[1];
    const int model_pixels = model_shape[0] * model_shape[1];
    letterbox_buf = new uint8_t[model_pixels]();
    for (int i = 0; i < RPS_MAX_RUNTIME_FRAME_GAP; i++) {
        frame_history[i] = new uint8_t[model_pixels]();
    }
    history_head = 0;
    history_count = 0;

    char* model_path_cstr = const_cast<char*>(model_path.c_str());
    model_id = ssne_loadmodel(model_path_cstr, SSNE_STATIC_ALLOC);

    const uint32_t model_width = static_cast<uint32_t>(model_shape[0]);
    const uint32_t model_height = static_cast<uint32_t>(model_shape[1]);
    diff_tensor = create_tensor(model_width, model_height, SSNE_Y_8, SSNE_BUF_AI);
    inputs[0] = create_tensor(model_width, model_height, SSNE_Y_8, SSNE_BUF_AI);
    memset(&outputs[0], 0, sizeof(ssne_tensor_t));

    PrintRuntimeRpsParams();
    if (RPS_DUMP_A1_INPUTS) EnsureA1InputDumpDir();
}

void RPSCLASSIFIER::Predict(ssne_tensor_t* img_in, RpsResult* result) {
    float probs[APP_GESTURE_COUNT] = {0.f, 0.f, 0.f, 0.f};
    RunSingleFrameInference(img_in, probs);

    float confidence = 0.f;
    GestureClass gesture = utils::ArgmaxProbs(probs, &confidence);
    if (gesture != GestureClass::IDLE && confidence < 0.40f) {
        gesture = GestureClass::IDLE;
        confidence = 0.f;
    }

    temporal_buffer.Push(gesture, confidence);
    UpdateStateMachine(gesture, confidence, result);
}

void RPSCLASSIFIER::Release() {
    if (letterbox_buf) {
        delete[] letterbox_buf;
        letterbox_buf = nullptr;
    }
    for (int i = 0; i < RPS_MAX_RUNTIME_FRAME_GAP; i++) {
        if (frame_history[i]) {
            delete[] frame_history[i];
            frame_history[i] = nullptr;
        }
    }
    if (get_data(diff_tensor) != nullptr) release_tensor(diff_tensor);
    if (get_data(inputs[0]) != nullptr) release_tensor(inputs[0]);
    memset(&diff_tensor, 0, sizeof(diff_tensor));
    memset(&inputs[0], 0, sizeof(inputs[0]));
    outputs[0].data = nullptr;
    if (pipe_offline != nullptr) {
        ReleaseAIPreprocessPipe(pipe_offline);
        pipe_offline = nullptr;
    }
    history_head = 0;
    history_count = 0;
    frame_pixels = 0;
    frame_count = 0;
}
